Repository zalando/restful-api-guidelines, pull requests merged in 2018-10, with the labels that each got.

#454 feat: link pagination with query parameters and improve wording (#445)
  chapters/naming.adoc
  chapters/pagination.adoc
Labels: discussion, editorial, enhancement

#459 editiorial: add link to the collection format rule (#458)
  chapters/naming.adoc
Labels: editorial, enhancement

#374 Indicate ordering key in event type definition (#245)
  .gitignore
  chapters/events.adoc
Labels: guideline-change
