Repository zalando/restful-api-guidelines, pull requests merged in 2018-07, with the labels that each got.

#421 Added sentence about disallowing maps from being top level objects
  chapters/compatibility.adoc
Labels: enhancement, guideline-change

#423 Cleared up sentence about OPTIONS method
  chapters/http-requests.adoc
Labels: editorial

#408 Change guideline to use only http status codes from list
  chapters/http-status-codes-and-errors.adoc
Labels: discussion, enhancement, guideline-change

#419 fix: get the raw title of the pull request (#418)
  travis_deploy.sh
Labels: bug, build

#425 editorial: explicitly relate review obligation to api audience
  chapters/general-guidelines.adoc
Labels: editorial

#416 editorial: remove redundancies in API Identifier motivation
  chapters/meta-information.adoc
Labels: editorial

#422 Event types include Audience definition
  chapters/events.adoc
Labels: guideline-change
