Repository zalando/restful-api-guidelines, pull requests merged in 2018-03, with the labels that each got.

#363 Suggestion to improve api-first principles.
  chapters/design-principles.adoc
Labels: editorial, enhancement

#368 correct link
  chapters/json-guidelines.adoc
Labels: bug

#334 clarify rule 196, fixes #302
  chapters/events.adoc
Labels: editorial, enhancement

#369 improve guidance on response (status code) documentation
  chapters/http.adoc
Labels: discussion, editorial, enhancement
