Repository zalando/restful-api-guidelines, pull requests merged in 2018-06, with the labels that each got.

#350 Updated guidelines to match new Zalando naming schema
  .gitignore
  chapters/changelog.adoc
  chapters/events.adoc
  chapters/naming.adoc
  chapters/security.adoc
  index.adoc
Labels: enhancement, guideline-change

#395 Improve title requirements
  chapters/meta-information.adoc
Labels: editorial, enhancement

#411 feat: use the title of the origin PR for Zally notification (#409)
  travis_deploy.sh
Labels: build

#413 Relax functional naming requirement and improve wording of guidance
  chapters/naming.adoc
Labels: enhancement, guideline-change

#410 feat: improved definition of same api for x-api-id (#378)
  chapters/meta-information.adoc
Labels: enhancement
