Repository zalando/restful-api-guidelines, pull requests merged in 2019-10, with the labels that each got.

#543 remove rule 206
  chapters/events.adoc
Labels: guideline-change

#545 Fix typo in rule 145
  chapters/resources.adoc
Labels: bug, editorial

#546 feat: clarified default on fields rule; cleaned up code; fixed bugs (#533)
  MAINTAINERS
  chapters/performance.adoc
Labels: editorial, enhancement
