Repository zalando/restful-api-guidelines, pull requests merged in 2019-06, with the labels that each got.

#503 feat: improve prefer header specification (#503)
  chapters/best-practices.adoc
  chapters/common-headers.adoc
  chapters/compatibility.adoc
  chapters/deprecation.adoc
  chapters/http-status-codes-and-errors.adoc
  chapters/meta-information.adoc
  chapters/performance.adoc
  chapters/proprietary-headers.adoc
  index.adoc
Labels: editorial, enhancement

#507 Remove X-App-Domain
  chapters/proprietary-headers.adoc
Labels: discussion, guideline-change

#511 feat: replace obsolete rfc 5988 against rfc 8288 (#509)
  chapters/hyper-media.adoc
  chapters/references.adoc
  index.adoc
Labels: bug, editorial

#508 feat: correct rule 154 (#505)
  chapters/http-requests.adoc
  index.adoc
Labels: discussion, enhancement
