Repository zalando/restful-api-guidelines, pull requests merged in 2019-09, with the labels that each got.

#532 feat: repair money object link (#531)
  .travis.yml
  chapters/common-data-types.adoc
  models/money-1.0.0.yaml
Labels: editorial, enhancement

#538 fix: fix reference to money object (#537)
  chapters/common-data-types.adoc
Labels: bug, editorial

#540 Customer_id example conflicts with backward compatibility constraints
  chapters/common-data-types.adoc
Labels: editorial

#539 feat: reorder chapters and remove duplicate rule (#534)
  build.sh
  chapters/data-formats.adoc
  chapters/json-guidelines.adoc
  index.adoc
Labels: bug, discussion, editorial

#541 Add hint about GraphQL Usage
  chapters/general-guidelines.adoc
Labels: editorial, enhancement
