Repository zalando/restful-api-guidelines, pull requests merged in 2019-07, with the labels that each got.

#510 feat: improved cursor guideline for get-with-body (#504)
  chapters/common-data-types.adoc
  chapters/http-requests.adoc
  chapters/hyper-media.adoc
  chapters/naming.adoc
  chapters/pagination.adoc
  index.adoc
Labels: discussion, enhancement, guideline-change

#516 Added naming convention for date-time properties
  chapters/common-data-types.adoc
  chapters/json-guidelines.adoc
  index.adoc
Labels: enhancement

#519 Made using the money object a MUST rule
  chapters/common-data-types.adoc
Labels: guideline-change

#517 Rephrased rule about null/absent properties
  .gitignore
  chapters/json-guidelines.adoc
  index.adoc
Labels: editorial, enhancement
