Repository zalando/restful-api-guidelines, pull requests merged in 2019-01, with the labels that each got.

#476 should not use /api as base path (#462)
  chapters/naming.adoc
Labels: enhancement, guideline-change

#479 feat: add idempotency guidance (#456)
  chapters/common-headers.adoc
  chapters/http-requests.adoc
  index.adoc
  sass/zalando.scss
  zalando.css
Labels: enhancement, guideline-change

#482 feat: improve guidance for caching support (#451)
  chapters/common-headers.adoc
  chapters/http-requests.adoc
  chapters/performance.adoc
  index.adoc
Labels: editorial, enhancement, guideline-change

#484 Description of Filter Parameter should refer to definition rule
  chapters/changelog.adoc
  chapters/performance.adoc
Labels: editorial, enhancement

#485 feat: improve linking of status codes, headers, etc (#481)
  chapters/best-practices.adoc
  chapters/common-data-types.adoc
  chapters/compatibility.adoc
  chapters/http-requests.adoc
  chapters/http-status-codes-and-errors.adoc
  chapters/resources.adoc
  index.adoc
Labels: editorial
