Repository zalando/restful-api-guidelines, pull requests merged in 2020-08, with the labels that each got.

#599 fix: fallback to older asciidoctor version (#597)
  .travis.yml
  BUILD.adoc
  MAINTAINERS
  Makefile
  build.sh
  check_rule_ids.sh
  generate_rules_json.sh
  index.adoc
  scripts/build-css.sh
  scripts/deploy-travis.sh
  scripts/generate-rules-json.sh
  scripts/new-rule-id.sh
Labels: build

#601 feat: adapt problem specification to guideline (#581)
  chapters/http-status-codes-and-errors.adoc
  models/problem-1.0.0.yaml
  models/problem-1.0.1.yaml
Labels: editorial, enhancement

#598 Usage of proprietary headers defined by Fashion Platform GW components
  chapters/proprietary-headers.adoc
Labels: enhancement, guideline-change

#600 feat: add guidance on path normalization (#571)
  chapters/naming.adoc
  chapters/resources.adoc
Labels: enhancement, guideline-change

#604 fix: image and table of contents (#602)
  Makefile
  chapters/hyper-media.adoc
  index.adoc
Labels: bug, editorial, formatting

#603 'self' as pseudo-identifier in resource paths
  chapters/naming.adoc
  chapters/resources.adoc
Labels: enhancement, guideline-change

#605 added link to Zalando Open-Source and GH Repo
  index.adoc
Labels: editorial

#606 clarify the UPPER_SNAKE_CASE rule for enums (#527)
  chapters/json-guidelines.adoc
Labels: guideline-change
