Repository zalando/restful-api-guidelines, pull requests merged in 2021-08, with the labels that each got.

#680 Update data formats per OpenAPI 3.1
  chapters/data-formats.adoc
  index.adoc
Labels: enhancement, no-zally-change

#681 Improve the wording when to use PUT for creation
  chapters/http-requests.adoc
Labels: enhancement, editorial

#682 Use only standard HTTP status codes registered via IANA
  chapters/http-status-codes-and-errors.adoc
Labels: enhancement, guideline-change

#683 PUT with server-side generated attributes
  chapters/http-requests.adoc
Labels: enhancement
