Repository zalando/restful-api-guidelines, pull requests merged in 2021-02, with the labels that each got.

#630 Update general-guidelines.adoc for typo fix
  chapters/general-guidelines.adoc
Labels: editorial

#627 Update general-guidelines.adoc
  chapters/general-guidelines.adoc
Labels: editorial, enhancement

#633 fix: typo in anchor for x-frontend-type header (#633)
  chapters/proprietary-headers.adoc
Labels: bug

#636 feat: update remote reference guideline (#631)
  chapters/general-guidelines.adoc
  index.adoc
Labels: guideline-change

#639 feat: improve cursor based pagination guideline (#587)
  chapters/best-practices.adoc
  chapters/common-data-types.adoc
  chapters/naming.adoc
  chapters/pagination.adoc
Labels: editorial, enhancement

#632 Add missing changelog entries (since mid 2018)
  chapters/changelog.adoc
Labels: editorial

#637 feat: add client note and improve json problem guideline (#624)
  chapters/http-status-codes-and-errors.adoc
Labels: editorial, enhancement
