Repository zalando/restful-api-guidelines, pull requests merged in 2021-06, with the labels that each got.

#666 Clearly differ between OpenAPI security scheme types and OAuth2
  chapters/security.adoc
  index.adoc
Labels: editorial, enhancement

#670 fix: parameter name to be not id
  chapters/resources.adoc
Labels: editorial, no-zally-change

#671 MUST use standard data formats (2)
  chapters/changelog.adoc
  chapters/common-headers.adoc
  chapters/data-formats.adoc
  chapters/json-guidelines.adoc
Labels: enhancement, guideline-change, zally-change

#673 fix: header formatting (#651)
  chapters/proprietary-headers.adoc
  index.adoc
Labels: editorial, enhancement, no-zally-change

#652 Update formatting for proprietary headers
  chapters/proprietary-headers.adoc
  index.adoc
Labels: editorial, enhancement, no-zally-change
