Repository zalando/restful-api-guidelines, pull requests merged in 2021-12, with the labels that each got.

#697 spelling and grammar fixes
  chapters/general-guidelines.adoc
  chapters/http-headers.adoc
  chapters/http-requests.adoc
  chapters/http-status-codes-and-errors.adoc
  chapters/meta-information.adoc
  chapters/performance.adoc
  models/problem-1.0.1.yaml
Labels: bug

#701 Fix Zally issue creation
  scripts/create-zally-issue.sh
Labels: bug

#706 feat: migrate master to main (#706)
  .github/workflows/build.yml
Labels: build

#704 More inclusive language: avoid whitelist / slave
  chapters/events.adoc
  chapters/http-headers.adoc
Labels: editorial

#702 feat: remove trailing spaces (#702)
  chapters/changelog.adoc
  chapters/compatibility.adoc
  chapters/data-formats.adoc
  chapters/deprecation.adoc
  chapters/design-principles.adoc
  chapters/events.adoc
  chapters/general-guidelines.adoc
  chapters/http-headers.adoc
  chapters/http-requests.adoc
  chapters/http-status-codes-and-errors.adoc
  chapters/json-guidelines.adoc
  chapters/meta-information.adoc
  chapters/performance.adoc
  chapters/security.adoc
  chapters/urls.adoc
Labels: formatting
