Repository zalando/restful-api-guidelines, pull requests merged in 2022-01, with the labels that each got.

#708 Fix capitalization of X-Device-* headers.
  index.adoc
Labels: bug, editorial

#707 clean-up 'internal links'
  chapters/events.adoc
  chapters/general-guidelines.adoc
  chapters/http-headers.adoc
  chapters/hyper-media.adoc
  chapters/introduction.adoc
  chapters/json-guidelines.adoc
  chapters/meta-information.adoc
  index.adoc
Labels: formatting

#712 replace dead letter queue
  chapters/events.adoc
Labels: editorial, no-zally-change

#711 More master→main fixes
  chapters/events.adoc
  chapters/general-guidelines.adoc
  chapters/security.adoc
  chapters/urls.adoc
Labels: bug, editorial

#713 bring the change log up-to-date
  chapters/changelog.adoc
Labels: enhancement, editorial, no-zally-change

#710 Add empty lines between chapter includes
  chapters/api-operation.adoc
  chapters/changelog.adoc
  chapters/introduction.adoc
  chapters/json-guidelines.adoc
  chapters/meta-information.adoc
  chapters/tooling.adoc
  chapters/urls.adoc
  index.adoc
Labels: bug, formatting, no-zally-change
