Repository zalando/restful-api-guidelines, pull requests merged in 2023-10, with the labels that each got.

#762 Apply working draft content to status codes
  chapters/compatibility.adoc
  chapters/http-status-codes-and-errors.adoc
  index.adoc
  sass/zalando.scss
  zalando.css
Labels: enhancement, formatting, editorial

#773 refactor: RFC 9457 obsoletes 7807, refer to it
  chapters/http-status-codes-and-errors.adoc
  chapters/references.adoc
  index.adoc
  models/problem-1.0.1.yaml
Labels: editorial

#778 feat: improve script quality (#778)
  scripts/build-css.sh
  scripts/create-zally-issue.sh
Labels: enhancement

#771 meta-information: do not copy the API-ID
  chapters/meta-information.adoc
Labels: guideline-change, no-zally-change

#777 add more examples to query parameters
  chapters/http-requests.adoc
Labels: enhancement, guideline-change

#783 fix: using headers anchor (#783)
  chapters/http-headers.adoc
  chapters/http-requests.adoc
Labels: bug, no-zally-change
