Repository zalando/restful-api-guidelines, pull requests merged in 2023-11, with the labels that each got.

#784 feat: add exception for partner IAM (#767)
  chapters/security.adoc
Labels: enhancement, guideline-change, zally-change

#785 feat: add new rule to prefer single resources (#764)
  chapters/json-guidelines.adoc
  index.adoc
Labels: enhancement, guideline-change, no-zally-change

#786 feat: ensure macos compatibility (#780)
  scripts/generate-includes.sh
Labels: bug, build

#788 feat: improve guidance on total counts (#731)
  chapters/http-headers.adoc
  chapters/pagination.adoc
  models/headers-1.0.0.yaml
Labels: enhancement, formatting, editorial, no-zally-change

#787 new rule: may use asynchronous processing
  chapters/http-requests.adoc
  chapters/http-status-codes-and-errors.adoc
Labels: enhancement, guideline-change, zally-change
