Repository zalando/restful-api-guidelines, pull requests merged in 2023-05, with the labels that each got.

#756 Reformat status codes into sections
  BUILD.adoc
  Makefile
  chapters/http-status-codes-and-errors.adoc
  index.adoc
  sass/zalando.scss
  zalando.css
Labels: enhancement, formatting, editorial

#759 feat: must sanitize json payload (#734)
  chapters/json-guidelines.adoc
Labels: guideline-change, no-zally-change

#760 feat: improve headers
  models/request-headers-1.0.0.yaml
  models/response-headers-1.0.0.yaml
Labels: enhancement, discussion, editorial, no-zally-change
