Repository zalando/restful-api-guidelines, pull requests merged in 2024-04, with the labels that each got.

#803 add deprecation hint to request vs. response header definition files
  models/request-headers-1.0.0.yaml
  models/response-headers-1.0.0.yaml
Labels: formatting, editorial

#802 fix: asciidoc build to run as user (#802)
  Makefile
Labels: bug

#804 Remove sort example from simple query language (236)
  chapters/http-requests.adoc
Labels: enhancement, editorial
