Repository zalando/restful-api-guidelines, pull requests merged in 2024-03, with the labels that each got.

#794 Update security section about uid scope
  chapters/security.adoc
Labels: enhancement, editorial

#800 Fix typo in introduction.adoc
  chapters/introduction.adoc
Labels: discussion

#799 Add best practices section for rule 108
  chapters/best-practices.adoc
  chapters/compatibility.adoc
  chapters/http-requests.adoc
Labels: enhancement
