Repository zalando/restful-api-guidelines, pull requests merged in 2024-06, with the labels that each got.

#810 Link rule 127 (duration / period) from rule 238
  chapters/data-formats.adoc
Labels: enhancement, no-zally-change

#811 Relax naming convention for date/time properties
  chapters/json-guidelines.adoc
Labels: guideline-change, zally-change

#807 clarity on x-extensible-enum usage for events
  chapters/compatibility.adoc
  chapters/events.adoc
Labels: editorial, no-zally-change
