Repository zalando/restful-api-guidelines, pull requests merged in 2025-04, with the labels that each got.

#825 Fix typo in "Prefered" Header section
  models/headers-1.0.0.yaml
Labels: editorial, minor

#830 Update RFC links in rule 243
  chapters/http-status-codes-and-errors.adoc
Labels: editorial, no-zally-change, bugfix

#832 Update RFC links in request and response header models
  index.adoc
  models/request-headers-1.0.0.yaml
  models/response-headers-1.0.0.yaml
Labels: editorial, no-zally-change, minor

#835 Deduplicate and simplify custom header example (X-Device-Type)
  chapters/http-headers.adoc
Labels: documentation
